"""Initial migration

Revision ID: e436130da3b8
Revises: 09aa64a90458
Create Date: 2024-06-30 12:56:10.024442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e436130da3b8'
down_revision = '09aa64a90458'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
